services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
 
    App\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']
 
        #App\Controller\LoginController:
        #   arguments:
        #   $jwtTtl: '%jwt_ttl%'
