services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
 
    App\Util\:
        resource: '../../src/Util'
 
    App\Util\JwtUtil:
        arguments:
            $jwtAlgorithm: '%jwt_algorithm%'
            $jwtPrivateKey: '%jwt_private_key%'
            $jwtPublicKey: '%jwt_public_key%'
