#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#api_login_check:
#    path: /api/login_check
login:
    path: /login
    methods: [POST]
    controller: App\Controller\LoginController::login
